/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class Receptor extends javax.swing.JFrame {

    String url;
    String user;
    String pass;
    Connection conectar;
    Statement sentencia;
    DefaultTableModel modelo;

    public Receptor() {
        initComponents();
        setLocationRelativeTo(null);
        //coneexoion con la base de datos 
        url = "jdbc:mysql://127.0.0.1:3607/prueba";
        user = "root";
        pass = "";
        //creacion de la tabla que muestra platillo, cantidad y precio
        modelo = new DefaultTableModel();
        modelo.addColumn("PLATILLO");
        modelo.addColumn("PRECIO");
        modelo.addColumn("CANTIDAD");
        txtPlatillo.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        MostrarFecha();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNum_Orden = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPlatillo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNombre_Cli = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRecibe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPlatillo1 = new javax.swing.JLabel();
        lblPlatillo3 = new javax.swing.JLabel();
        lblPlatillo2 = new javax.swing.JLabel();
        lblPlatillo4 = new javax.swing.JLabel();
        lblPlatillo6 = new javax.swing.JLabel();
        lblPlatillo5 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        realizaBtn1 = new javax.swing.JButton();
        btnCambio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mr BurguerJ: Ventana de Receptor");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 6));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("NOMBRE DEL CLIENTE:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-1.png"))); // NOI18N

        txtNum_Orden.setEditable(false);
        txtNum_Orden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNum_OrdenMouseClicked(evt);
            }
        });
        txtNum_Orden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum_OrdenKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("NOMBRE DEL PLATILLO:");

        txtPlatillo.setEditable(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("NUMERO DE ORDEN:");

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setForeground(new java.awt.Color(255, 255, 0));
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("CONECTAR CON LA BASE DE DATOS");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("FECHA: AA/MM/DD");

        txtNombre_Cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombre_CliMouseClicked(evt);
            }
        });
        txtNombre_Cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_CliKeyTyped(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("TOTAL A PAGAR $ ");

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("RECIBE $");

        txtRecibe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRecibeMouseClicked(evt);
            }
        });
        txtRecibe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRecibeKeyTyped(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("CAMBIO $");

        txtCambio.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("PRECIO: $");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtFecha.setEditable(false);
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("CANTIDAD:");

        txtPrecio.setEditable(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("MENÚ:");

        lblPlatillo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPlatillo1.setForeground(new java.awt.Color(255, 255, 0));
        lblPlatillo1.setText("Hamburguesa Hawaiana");
        lblPlatillo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatillo1MouseClicked(evt);
            }
        });

        lblPlatillo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatillo3.setForeground(new java.awt.Color(255, 255, 0));
        lblPlatillo3.setText("Hamburguesa BBQ");
        lblPlatillo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatillo3MouseClicked(evt);
            }
        });

        lblPlatillo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatillo2.setForeground(new java.awt.Color(255, 255, 0));
        lblPlatillo2.setText("Hamburguesa Guacamole");
        lblPlatillo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatillo2MouseClicked(evt);
            }
        });

        lblPlatillo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatillo4.setForeground(new java.awt.Color(255, 255, 0));
        lblPlatillo4.setText("Torta al pastor");
        lblPlatillo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatillo4MouseClicked(evt);
            }
        });

        lblPlatillo6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatillo6.setForeground(new java.awt.Color(255, 255, 0));
        lblPlatillo6.setText("Pepsi 2 litros");
        lblPlatillo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatillo6MouseClicked(evt);
            }
        });

        lblPlatillo5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatillo5.setForeground(new java.awt.Color(255, 255, 0));
        lblPlatillo5.setText("Orden de papas");
        lblPlatillo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatillo5MouseClicked(evt);
            }
        });

        btnVisualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 0));
        btnVisualizar.setText("VISUALIZAR");
        btnVisualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseClicked(evt);
            }
        });
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLATILLO", "PRECIO", "CANTIDAD"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla);

        realizaBtn1.setBackground(new java.awt.Color(0, 0, 0));
        realizaBtn1.setForeground(new java.awt.Color(255, 255, 0));
        realizaBtn1.setText("INSERTAR ORDEN");
        realizaBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        realizaBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizaBtn1MouseClicked(evt);
            }
        });
        realizaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaBtn1ActionPerformed(evt);
            }
        });

        btnCambio.setBackground(new java.awt.Color(0, 0, 0));
        btnCambio.setForeground(new java.awt.Color(255, 255, 0));
        btnCambio.setText("DAR CAMBIO");
        btnCambio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnCambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambioMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("SELECCIONE UN PLATILLO:");

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 0));
        btnRegresar.setText("REGRESAR AL INICIO");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(187, 187, 187))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPlatillo2)
                                            .addComponent(lblPlatillo1)
                                            .addComponent(lblPlatillo3)
                                            .addComponent(lblPlatillo4)
                                            .addComponent(lblPlatillo5)
                                            .addComponent(lblPlatillo6))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCambio)
                        .addGap(28, 28, 28)
                        .addComponent(realizaBtn1)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(134, 134, 134))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum_Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlatillo, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtNombre_Cli)
                                    .addComponent(txtPrecio)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnVisualizar)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatillo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatillo4)
                        .addGap(5, 5, 5)
                        .addComponent(lblPlatillo5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatillo6)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNum_Orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNombre_Cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(realizaBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mensaje("Conectando...");
        try {
            conectar = (Connection) DriverManager.getConnection(url, user, pass);
            mensaje("Conección exitosa");
            sentencia = conectar.createStatement();
            idIncrementable();
        } catch (SQLException e) {
            mensaje("ERROR..." + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void realizaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaBtn1ActionPerformed
        // TODO add your handling code here
        String qryInsert = "insert into pedido " + "(num_orden, fecha, nombre_cliente, platillo, cantidad, precio) values "
                + "('" + txtNum_Orden.getText() + "','" + txtFecha.getText() + "','" + txtNombre_Cli.getText() + "','" + txtPlatillo.getText() + "','"
                + txtCantidad.getText() + "','" + txtPrecio.getText() + "')";
        String qryInsert1 = "insert into pago " + "(total_pago, recibe_dinero, cambio_dinero) values "
                + "('" + txtTotal.getText() + "','" + txtRecibe.getText() + "','" + txtCambio.getText() + "')";
        try {

            mensaje("Insertando...");
            sentencia.executeUpdate(qryInsert);
            sentencia.executeUpdate(qryInsert1);
            int fila = Tabla.getRowCount();
            for (int i = fila - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            MrBurguerJRealizado rece = new MrBurguerJRealizado();
            rece.setVisible(true);
            String num_orden;
            num_orden = txtNum_Orden.getText();
            rece.txtRecibe.setText(num_orden);

            idIncrementable();
            MostrarFecha();
            txtNombre_Cli.setText("");
            txtPlatillo.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtTotal.setText("");
            txtRecibe.setText("");
            txtCambio.setText("");

        } catch (SQLException e) {
            mensaje("ERROR..." + e.getMessage());

        }

    }//GEN-LAST:event_realizaBtn1ActionPerformed

    private void txtRecibeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRecibeMouseClicked
        // TODO add your handling code here:

        try {
            int precio = Integer.parseInt(txtPrecio.getText());
            int cantidad = Integer.parseInt(txtCantidad.getText());
            int total;
            total = precio * cantidad;
            txtTotal.setText(total + "");
            if (txtPrecio.getText() == "" && txtCantidad.getText() == "" && txtTotal.getText() == "") {

            }
        } catch (Exception e) {
            mensaje("Error, campos vacios ");
        }


    }//GEN-LAST:event_txtRecibeMouseClicked

    private void btnCambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambioMouseClicked
        // TODO add your handling code here:
        try {
            double total = Double.parseDouble(txtTotal.getText());
            double recibe = Double.parseDouble(txtRecibe.getText());
            double resultado;
            if (total < recibe) {
                resultado = recibe - total;
                txtCambio.setText(String.valueOf(resultado));
            } else if (total > recibe) {
                resultado = total - recibe;
                txtCambio.setText(String.valueOf(resultado));
            } else if (total == recibe) {
                resultado = 0;
                txtCambio.setText(String.valueOf(resultado));
            }
            if (txtPrecio.getText() == "" && txtTotal.getText() == "") {

            }
        } catch (Exception e) {
            mensaje("Error no ingresó cuanto recibe en campo recibe ");
        }

    }//GEN-LAST:event_btnCambioMouseClicked

    private void btnVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseClicked
        // TODO add your handling code here:
        try {
            String[] cabecera = new String[3];
            cabecera[0] = txtPlatillo.getText();
            cabecera[1] = txtPrecio.getText();
            cabecera[2] = txtCantidad.getText();

            //cambiar el ancho de la columna
            Tabla.getColumnModel().getColumn(0).setPreferredWidth(130);
            //ajustar en el centro la columna
            DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            Tabla.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
            Tabla.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
            Tabla.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            modelo.addRow(cabecera);
        } catch (Exception e) {
            mensaje("Error");
        }

    }//GEN-LAST:event_btnVisualizarMouseClicked

    private void txtNum_OrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNum_OrdenMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNum_OrdenMouseClicked

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccionar la fila");
        }

    }//GEN-LAST:event_btnBorrarMouseClicked

    private void realizaBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizaBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_realizaBtn1MouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void lblPlatillo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatillo1MouseClicked
        // TODO add your handling code here:
        String platillo1 = lblPlatillo1.getText();

        if (txtPlatillo.getText() == "") {
            txtPlatillo.setText(platillo1);
            txtPrecio.setText("55");
            btnVisualizar.setEnabled(true);
        } else {
            txtPlatillo.setText("");
            txtPlatillo.setText(platillo1);
            txtPrecio.setText("55");
            btnVisualizar.setEnabled(true);
        }
    }//GEN-LAST:event_lblPlatillo1MouseClicked

    private void lblPlatillo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatillo2MouseClicked
        // TODO add your handling code here:
        String platillo2 = lblPlatillo2.getText();

        if (txtPlatillo.getText() == "") {
            txtPlatillo.setText(platillo2);
            txtPrecio.setText("60");
            btnVisualizar.setEnabled(true);
        } else {
            txtPlatillo.setText("");
            txtPlatillo.setText(platillo2);
            txtPrecio.setText("60");
            btnVisualizar.setEnabled(true);
        }
    }//GEN-LAST:event_lblPlatillo2MouseClicked

    private void lblPlatillo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatillo3MouseClicked
        // TODO add your handling code here:
        String platillo3 = lblPlatillo3.getText();

        if (txtPlatillo.getText() == "") {
            txtPlatillo.setText(platillo3);
            txtPrecio.setText("80");
            btnVisualizar.setEnabled(true);
        } else {
            txtPlatillo.setText("");
            txtPlatillo.setText(platillo3);
            txtPrecio.setText("80");
            btnVisualizar.setEnabled(true);
        }
    }//GEN-LAST:event_lblPlatillo3MouseClicked

    private void lblPlatillo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatillo4MouseClicked
        // TODO add your handling code here:
        String platillo4 = lblPlatillo4.getText();

        if (txtPlatillo.getText() == "") {
            txtPlatillo.setText(platillo4);
            txtPrecio.setText("40");
            btnVisualizar.setEnabled(true);
        } else {
            txtPlatillo.setText("");
            txtPlatillo.setText(platillo4);
            txtPrecio.setText("40");
            btnVisualizar.setEnabled(true);
        }
    }//GEN-LAST:event_lblPlatillo4MouseClicked

    private void lblPlatillo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatillo5MouseClicked
        // TODO add your handling code here:
        String platillo5 = lblPlatillo5.getText();

        if (txtPlatillo.getText() == "") {
            txtPlatillo.setText(platillo5);
            txtPrecio.setText("30");
            btnVisualizar.setEnabled(true);
        } else {
            txtPlatillo.setText("");
            txtPlatillo.setText(platillo5);
            txtPrecio.setText("30");
            btnVisualizar.setEnabled(true);
        }
    }//GEN-LAST:event_lblPlatillo5MouseClicked

    private void lblPlatillo6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatillo6MouseClicked
        // TODO add your handling code here:
        String platillo6 = lblPlatillo6.getText();

        if (txtPlatillo.getText() == "") {
            txtPlatillo.setText(platillo6);
            txtPrecio.setText("35");
            btnVisualizar.setEnabled(true);
        } else {
            txtPlatillo.setText("");
            txtPlatillo.setText(platillo6);
            txtPrecio.setText("35");
            btnVisualizar.setEnabled(true);
        }
    }//GEN-LAST:event_lblPlatillo6MouseClicked

    private void txtNum_OrdenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum_OrdenKeyTyped
        // TODO add your handling code here:
        String contenido = String.valueOf(evt.getKeyChar());
        if (!(contenido.matches("[0-9]"))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNum_OrdenKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
        String contenido = String.valueOf(evt.getKeyChar());
        if (!(contenido.matches("[0-9/]"))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtNombre_CliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_CliKeyTyped
        // TODO add your handling code here:
        String contenido = String.valueOf(evt.getKeyChar());
        char caracter = evt.getKeyChar();
        if (!(contenido.matches("[a-zA-Z ]"))) {
            evt.consume();
        }
        if (Character.isLowerCase(caracter)) {
            evt.setKeyChar(Character.toUpperCase(caracter));
        }
    }//GEN-LAST:event_txtNombre_CliKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        String contenido = String.valueOf(evt.getKeyChar());
        if (!(contenido.matches("[0-9]"))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        String contenido = String.valueOf(evt.getKeyChar());
        if (!(contenido.matches("[0-9]"))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtRecibeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecibeKeyTyped
        // TODO add your handling code here:
        String contenido = String.valueOf(evt.getKeyChar());
        if (!(contenido.matches("[0-9]"))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRecibeKeyTyped

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        inicioDesesionGeneral inicio = new inicioDesesionGeneral();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaMouseClicked

    private void txtNombre_CliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombre_CliMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombre_CliMouseClicked
    static void mensaje(String texto) {
        JOptionPane.showMessageDialog(null, texto);
    }

    public void idIncrementable() {
        int j;
        String c = "";
        String qrySelect = "Select max(num_orden) AS num_orden from pedido ";
        ResultSet resultado;
        String id = "";
        int orden = 0;
        int cont = 1;
        int cant;

        try {
            sentencia = conectar.createStatement();
            resultado = sentencia.executeQuery(qrySelect);
            if (resultado.next()) {
                c = resultado.getString("num_orden");
            }
            if (c == null) {
                txtNum_Orden.setText("1");
            } else {
                orden = Integer.parseInt(c);
                char r1 = c.charAt(0);
                String juntar = "" + r1;
                int var = Integer.parseInt(juntar);
                cant = cont + var;
                txtNum_Orden.setText("" + cant);

                if (orden > 9) {
                    r1 = c.charAt(0);
                    char r2 = c.charAt(1);
                    juntar = "" + r1 + r2;
                    var = Integer.parseInt(juntar);
                    cant = cont + var;
                    txtNum_Orden.setText("" + cant);
                }
                if (orden > 99) {
                    r1 = c.charAt(0);
                    char r2 = c.charAt(1);
                    char r3 = c.charAt(2);
                    juntar = "" + r1 + r2 + r3;
                    var = Integer.parseInt(juntar);
                    cant = cont + var;
                    txtNum_Orden.setText("" + cant);
                }
                if (orden > 999) {
                    r1 = c.charAt(0);
                    char r2 = c.charAt(1);
                    char r3 = c.charAt(2);
                    char r4 = c.charAt(3);
                    juntar = "" + r1 + r2 + r3 + r4;
                    var = Integer.parseInt(juntar);
                    cant = cont + var;
                    txtNum_Orden.setText("" + cant);
                }
            }
        } catch (Exception e) {
            mensaje("Error con el numero de orden");
        }

    }

    public void MostrarFecha() {
        this.Tabla.setModel(modelo);
        //Asignando a los campos de texto de dia y mes la fecha actual de cada dia
        Calendar cal = Calendar.getInstance();
        String fecha;
        String mes;
        if (cal.get(Calendar.MONTH) < 10) {
            fecha = cal.get(Calendar.YEAR) + "/" + "0" + ((cal.get(Calendar.MONTH)) + 1) + "/" + cal.get(Calendar.DATE);
            this.txtFecha.setText(fecha);

        } else {
            fecha = cal.get(Calendar.YEAR) + "/" + ((cal.get(Calendar.MONTH)) + 1) + "/" + cal.get(Calendar.DATE);
            this.txtFecha.setText(fecha);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCambio;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnVisualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblPlatillo1;
    private javax.swing.JLabel lblPlatillo2;
    private javax.swing.JLabel lblPlatillo3;
    private javax.swing.JLabel lblPlatillo4;
    private javax.swing.JLabel lblPlatillo5;
    private javax.swing.JLabel lblPlatillo6;
    private javax.swing.JButton realizaBtn1;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre_Cli;
    private javax.swing.JTextField txtNum_Orden;
    private javax.swing.JTextField txtPlatillo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRecibe;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
